export const techIcons: { [key: string] : string } = {
    "Express.js" : "/svg-icons/expressjs-dark.svg",
    "Next.js" : "/svg-icons/nextjs.svg",
    "Bootstrap CSS" : "/svg-icons/bootstrap.svg",
    "Cypress" : "/svg-icons/cypress.svg",
    "Django" : "/svg-icons/django.svg",
    "JavaScript" : "/svg-icons/javascript.svg",
    "Docker" : "/svg-icons/docker.svg",
    "Knex.js" : "/svg-icons/knexjs.svg",
    "Node.js" : "/svg-icons/nodejs.svg",
    "PostgreSQL" : "/svg-icons/postgresql.svg",
    "Pytest" : "/svg-icons/pytest.svg",
    "Python" : "/svg-icons/python.svg",
    "React.js" : "/svg-icons/reactjs.svg",
    "Svelte.js" : "/svg-icons/sveltejs.svg",
    "TypeScript" : "/svg-icons/typescript.svg",
    "Vite" : "/svg-icons/vite.svg",
    "Tailwind" : "/svg-icons/tailwindcss.svg",
    "Vercel" : "/svg-icons/vercel-dark.svg",
    "LinkedIn" : "/svg-icons/linkedin.svg",
    "GitHub" : "/svg-icons/github.svg",
}